name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ZT
      run: curl -s https://install.zerotier.com | sudo bash
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
    - name: Join ZT
      env:
        zt_id: ${{ secrets.zt_id }}
      run: bash -c 'echo hi'
