name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ZT
      run: curl -s https://install.zerotier.com | sudo bash
    - name: Join ZT
      env:
        zt_id: ${{ secrets.zt_id }}
      run: sudo zerotier-cli join $zt_id
    - name: Install python dependencies
      run: pip install rq
    - name: Start tests
      run: /home/runner/.local/bin/rq worker --url redis://172.29.8.119:6379/